### ISSUE TITLE
Can not install this package

### ISSUE THREAD

**Issue by Mingruis** [skschum/MFAssignR#18]
Hi,
I am trying to install this package to do the formula prediction. However, there is a error massage in R ,  when installing it by "install_github("skschum/MFAssignR")".
![image](https://user-images.githubusercontent.com/54156546/83732237-99470280-a600-11ea-873e-93fd796a75f9.png)

Many thanks.

**Comment by skschum** [comment]
Hello,
Please try "install_github("skschum/MFAssignR/MFAssignR")", I think it should work. If not please let me know and I will look at it again. 
You can also directly download the package from GitHub and install it with the devtools "install" function assuming you set the working directory in R to where you have stored the MFAssignR folder.
Please let me know if you have any other questions or issues.
Thanks.

**Comment by Mingruis** [comment]
Thanks you so much! I have installed successfully!

**Comment by Mingruis** [comment]
One more question: what should the data frame look like? If I only provide m/z of peaks, an error occurs.
 Thanks for your help.
![image](https://user-images.githubusercontent.com/54156546/83824592-c987b300-a68b-11ea-9c2f-02d6e3dc952f.png)

**Comment by skschum** [comment]
The input dataframe should have two columns, m/z and abundance, in that
order. If you don't have an abundance value you can just add a column
filled with 1's as a placeholder, this column can have any name you want.
Let me know if this helps or if you have any other questions.

**Comment by montmasis** [comment]
Hi, 
having also issues to install. Tried with devtools github, or also locally by manually downloading the folder.
However, I always get error messages during the installation that some dependencies are not working / not able to remove previous installations
e.g.

package ‘backports’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘backports’

I tried also checking that I run R as admin, but still get these errors..
I am running R 3.6.3

Any tips?

Thanks

Stefano

**Comment by skschum** [comment]
Hello Stefano,

Thank you for your interest in the package. For your issue with
'backports', I think it is more of a hang up that R and Rstudio have as
opposed to MFAssignR itself, I encountered the same problem with 'dplyr'
when trying to recreate your problem. I would suggest updating 'backports'
individually and then trying to install MFAssignR, or just not update
'backports' at all. I don't know that backports is something that plays a
direct role with MFAssignR, so it should be fine.

For the ion question, yes, pos and neg correspond only to standard
protonation and deprotonation. However, you can do odd electron ionization
([M]+ and [M]-) if you add POEx = 1 (positive mode) or NOEx = 1 (negative
mode) to your inputs (analogous to the heteroatoms). Currently MFAssignR
only supports protonation/deprotonation, odd electron, and sodium adduct
ionization mechanisms, though I will look into adding more types of
ionization when I can.

Let me know if you have any additional questions, or if my answers are
unclear. If you have any more problems, please let me know I and will try
to address them as best I can.

Thanks,
Simeon

**Comment by skschum** [comment]
I am going to close this issue thread at this point. If there are any other issues with installing MFAssignR feel free to start another issue.
