### ISSUE TITLE
IsoFiltR problem

### ISSUE THREAD

**Issue by simonbenk** [skschum/MFAssignR#21]
Dear Simeon

great package! I'm encountering an issue when trying to apply IsoFiltR() to some of my mass lists, while others work perfectly well. The error message I get is: 

> Error in `$<-.data.frame`(`*tmp*`, "Tag", value = "2C13") : 
>   replacement has 1 row, data has 0

I don't know what the origin of the error could be because most of my mass lists work just fine. However, I found that the error message can be recreated for example by subsetting mass lists that usually run well. 

Using only the first 3865 rows of the example data Raw_Neg_ML works fine

`IsoFiltR(MFAssignR::Raw_Neg_ML[1:3865,])`

but as soon as one more row is cut

`IsoFiltR(MFAssignR::Raw_Neg_ML[1:3864,])`

it breaks, resulting in the error stated above. 

I would greatly appreciate any help.

Best wishes,
Simon

**Comment by skschum** [comment]
Hello Simon,

Thanks for your interest in the package. I believe I have seen that problem
before and have made a fix for it that I just added to the MFAssignR
package on GitHub. Try the new version of IsoFiltR() and let me know if you
still encounter the same problem.

Thanks,
Simeon

**Comment by simonbenk** [comment]
Your fix did it, the error is gone.

Many thanks!

Simon
