### ISSUE TITLE
Is there any installation manual?

### ISSUE THREAD

**Issue by PowderL** [skschum/MFAssignR#24]
Is there any installation manual to install this package from the github? I have tried several times but failed still for cannot find this package with the 404 error. I used install_github method from devtools. I pasted the error information below:
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`skschum`) and repo name (`MFAssignR`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo

**Comment by skschum** [comment]
Hello,

There is no specific manual for installing from github, typically I suggest
that the user download the package directly from github and put it in a
directory on your computer and install it from there. The "Formula
Assignment Markdown Example.RMD" file in the Supplemental MFAssign Scripts
has the requisite lines of code and explanation for how to install
MFAssignR when the file packages are located on your computer.

I haven't tried using the install_github function to download MFAssignR so
I will look into it and try to change whatever permissions are required to
allow it to be used.

Hopefully this can be helpful to get you started with using the package, if
you have any other questions, please let me know and I will do what I can
to help.

Thanks,
Simeon

**Comment by PowderL** [comment]
Thanks for your timely reply. I followed the suggestion given by you and successfully installed the package.
Best wishes 
Jeffery
